import type { FontMap } from '../types/font';

const fontMap: FontMap = {
  // CAPITAL
  A: { layer: 'capital', frame: 0 },
  B: { layer: 'capital', frame: 1 },
  C: { layer: 'capital', frame: 2 },
  D: { layer: 'capital', frame: 3 },
  E: { layer: 'capital', frame: 4 },
  F: { layer: 'capital', frame: 5 },
  G: { layer: 'capital', frame: 6 },
  H: { layer: 'capital', frame: 7 },
  I: { layer: 'capital', frame: 8 },
  J: { layer: 'capital', frame: 9 },
  K: { layer: 'capital', frame: 10 },
  L: { layer: 'capital', frame: 11 },
  M: { layer: 'capital', frame: 12 },
  N: { layer: 'capital', frame: 13 },
  O: { layer: 'capital', frame: 14 },
  P: { layer: 'capital', frame: 15 },
  Q: { layer: 'capital', frame: 16 },
  R: { layer: 'capital', frame: 17 },
  S: { layer: 'capital', frame: 18 },
  T: { layer: 'capital', frame: 19 },
  U: { layer: 'capital', frame: 20 },
  V: { layer: 'capital', frame: 21 },
  W: { layer: 'capital', frame: 22 },
  X: { layer: 'capital', frame: 23 },
  Y: { layer: 'capital', frame: 24 },
  Z: { layer: 'capital', frame: 25 },

  // LOWERCASE
  a: { layer: 'lower', frame: 0 },
  b: { layer: 'lower', frame: 1 },
  c: { layer: 'lower', frame: 2 },
  d: { layer: 'lower', frame: 3 },
  e: { layer: 'lower', frame: 4 },
  f: { layer: 'lower', frame: 5 },
  g: { layer: 'lower', frame: 6 },
  h: { layer: 'lower', frame: 7 },
  i: { layer: 'lower', frame: 8 },
  j: { layer: 'lower', frame: 9 },
  k: { layer: 'lower', frame: 10 },
  l: { layer: 'lower', frame: 11 },
  m: { layer: 'lower', frame: 12 },
  n: { layer: 'lower', frame: 13 },
  o: { layer: 'lower', frame: 14 },
  p: { layer: 'lower', frame: 15 },
  q: { layer: 'lower', frame: 16 },
  r: { layer: 'lower', frame: 17 },
  s: { layer: 'lower', frame: 18 },
  t: { layer: 'lower', frame: 19 },
  u: { layer: 'lower', frame: 20 },
  v: { layer: 'lower', frame: 21 },
  w: { layer: 'lower', frame: 22 },
  x: { layer: 'lower', frame: 23 },
  y: { layer: 'lower', frame: 24 },
  z: { layer: 'lower', frame: 25 },

  // NUMBERS
  '0': { layer: 'num', frame: 0 },
  '1': { layer: 'num', frame: 1 },
  '2': { layer: 'num', frame: 2 },
  '3': { layer: 'num', frame: 3 },
  '4': { layer: 'num', frame: 4 },
  '5': { layer: 'num', frame: 5 },
  '6': { layer: 'num', frame: 6 },
  '7': { layer: 'num', frame: 7 },
  '8': { layer: 'num', frame: 8 },
  '9': { layer: 'num', frame: 9 },

  // SYMBOLS
  '.': { layer: 'sym', frame: 0 },
  ',': { layer: 'sym', frame: 1 },
  '/': { layer: 'sym', frame: 2 },
  '\\': { layer: 'sym', frame: 3 },
  ':': { layer: 'sym', frame: 4 },
  ';': { layer: 'sym', frame: 5 },
  "'": { layer: 'sym', frame: 6 },
  '"': { layer: 'sym', frame: 7 },
  '`': { layer: 'sym', frame: 8 },
  '?': { layer: 'sym', frame: 9 },
  '!': { layer: 'sym', frame: 10 },
  '@': { layer: 'sym', frame: 11 },
  '#': { layer: 'sym', frame: 12 },
  $: { layer: 'sym', frame: 13 },
  '%': { layer: 'sym', frame: 14 },
  '&': { layer: 'sym', frame: 15 },
  '^': { layer: 'sym', frame: 16 },
  '*': { layer: 'sym', frame: 17 },
  '-': { layer: 'sym', frame: 18 },
  '+': { layer: 'sym', frame: 19 },
  '=': { layer: 'sym', frame: 20 },
  _: { layer: 'sym', frame: 21 },
  '~': { layer: 'sym', frame: 22 },
  '(': { layer: 'sym', frame: 23 },
  ')': { layer: 'sym', frame: 24 },
  '{': { layer: 'sym', frame: 25 },
  '}': { layer: 'sym', frame: 26 },
  '[': { layer: 'sym', frame: 27 },
  ']': { layer: 'sym', frame: 28 },
  '<': { layer: 'sym', frame: 29 },
  '>': { layer: 'sym', frame: 30 },
  '|': { layer: 'sym', frame: 31 },
};

const getChar = (char: string) => {
  return fontMap[char] || fontMap['?'];
};

export default getChar;
